AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Album Registration System - Comparing Step Functions vs Durable Functions

Globals:
  Function:
    Timeout: 900
    Runtime: nodejs24.x
    MemorySize: 1024
    Architectures:
      - arm64

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/hello-world/
      Timeout: 30
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Format: esm
        Platform: node
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - index.mjs
        External:
          - '@aws-sdk/*'

  DurableFunctionExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: workflows/durable-function-example/
      Timeout: 900
      Environment:
        Variables:
          HELLO_WORLD_FUNCTION_ARN: !GetAtt HelloWorldFunction.Arn
      DurableConfig:
        ExecutionTimeout: 3600
        RetentionPeriodInDays: 7
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
        - LambdaInvokePolicy:
            FunctionName: !Ref HelloWorldFunction
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2022
        Format: esm
        Platform: node
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - index.mjs
        External:
          - '@aws-sdk/*'

Outputs:
  DurableFunctionExampleFunctionArn:
    Description: Durable function example ARN
    Value: !GetAtt DurableFunctionExampleFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DurableFunctionExampleFunctionArn'

  HelloWorldFunctionArn:
    Description: Hello World function ARN
    Value: !GetAtt HelloWorldFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-HelloWorldFunctionArn'
